ALTER TABLE "Playbook" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AuthorityRule" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Policy" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Tool" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
